// <auto-generated />
namespace KnockoutAndTypescript.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bank3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bank3));
        
        string IMigrationMetadata.Id
        {
            get { return "201706141022408_bank3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
