// <auto-generated />
namespace KnockoutAndTypescript.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Childreward : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Childreward));
        
        string IMigrationMetadata.Id
        {
            get { return "201706231200457_Child-reward"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
